export const login = {
  LOGIN_USER: 'LOGIN_USER',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  GET_USER: 'GET_USER',
  GET_USER_SUCCESS: 'GET_USER_SUCCESS',
  LOGOUT_USER: 'LOGOUT_USER',
};
export const categories = {
  GET_ALL_CATEGORIES: 'GET_ALL_CATEGORIES',
  GET_ALL_CATEGORIES_SUCCESS: 'GET_ALL_CATEGORIES_SUCCESS',
};
export const items = {
  GET_ITEMS_BY_CATEGORY: 'GET_ITEMS_BY_CATEGORY',
  GET_ITEMS_BY_CATEGORY_SUCCESS: 'GET_ITEMS_BY_CATEGORY_SUCCESS',
  GET_ITEM_BY_ID: 'GET_ITEM_BY_ID',
  GET_ITEM_BY_ID_SUCCESS: 'GET_ITEM_BY_ID_SUCCESS',
  GET_NEARBY_ITEMS: 'GET_NEARBY_ITEMS',
  GET_NEARBY_ITEMS_SUCCESS: 'GET_NEARBY_ITEMS_SUCCESS',
};
export const booking = {
  SAVE_ITEM_BOOKING: 'GET_ITEMS_BY_CATEGORY',
  SAVE_ITEM_BOOKING_SUCCESS: 'GET_ITEMS_BY_CATEGORY_SUCCESS',
};
