export const login = {
  LOGIN_USER: 'LOGIN_USER',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGOUT_USER: 'LOGOUT_USER',
};
export const categories = {
  GET_ALL_CATEGORIES: 'GET_ALL_CATEGORIES',
  GET_ALL_CATEGORIES_SUCCESS: 'GET_ALL_CATEGORIES_SUCCESS',
};
